### PR TITLE
feat: avoid fatal error

### PR DESCRIPTION
**Pull request by alexander-akait**
/cc @ludofischer @Semigradsky 

The main idea is avoid fatal error when we can't parse and keep value as it, should we use warning or error? Should we have options to change warning on error and versa vice.

### CODE REVIEW

**Comment by ludofischer** [comment]
> The main idea is avoid fatal error when we can't parse and keep value as it, should we use warning or error? Should we have options to change warning on error and versa vice.

In the context of cssnano I think it should be a warning, if the code reaches minification we assume the CSS is already tested and validated. There's already a way to [turn PostCSS warnings into errors](https://github.com/postcss/postcss#treat-warnings-as-errors), and I don't think adding the option to one plugin at a time is a common use case (why would you want to only error when there are `calc()` warnings but not on other warnings?)

**Comment by alexander-akait** [comment]
> why would you want to only error when there are calc() warnings but not on other warnings?

Because here he handle only calc :smile: 

Right now many developers get fatal errors due this using cssnano, we should fix it

**Comment by ludofischer** [comment]
I think this is fine, people can use a linter to prevent them from writing invalid CSS.

**Comment by alexander-akait** [comment]
@ludofischer anyway we should use postcss API for errors, no just throw an error

**Comment by ludofischer** [comment]
> @ludofischer anyway we should use postcss API for errors, no just throw an error

Yes, this should solve https://github.com/cssnano/cssnano/issues/910

**Comment by ludofischer** [comment]
Is this ready? I've received permissions on this repository so I could merge it.

**Comment by alexander-akait** [comment]
Ready, just want to ensure you review my changes

**Comment by ludofischer** [comment]
Looks fine, we can fix the quote formatting in a different PR as right now it's inconsistent throughout the code base.

**Review by ludofischer — APPROVED** [review]

**Comment by alexander-akait** [comment]
do you have access for publish?

**Comment by ludofischer** [comment]
> do you have access for publish?

No.

**Comment by alexander-akait** [comment]
@ludofischer Sorry for delay, added permission for `postcss-calc`

**Pull request merged**
