### PR TITLE
fix when decl is not a string

### PR DESCRIPTION
**Pull request by Casear**
when decl is a integer , the compiler will be failed

### CODE REVIEW

**Comment by MoOx** [comment]
Hum why a value would be an integer ?
I am guessing that loooots of plugins will have the same issue (poke @ai)

**Comment by Casear** [comment]
I use this css content.
```
.clearfix {
  *zoom: 1;
  &:before, &:after {
    content: " ";
    display: table;
  }
  &:after {
    clear: both;
  }
}
```
node property will be 
```
{
prop: '*zoom',
  value: 1
}
```

I got this error
TypeError: undefined is not a function

**Comment by ai** [comment]
@MoOx outdated postcss-mixins allows users to set integers to value. Now it normalize values to string, but I think some other plugins can brake AST too.

**Comment by MoOx** [comment]
So I guess a `String(decl.value).indexOf` should do the trick.
What about handling this in postcss in the value setter ? To avoid having to update all plugins ? (Because I think lots of plugin might have the exact same issue).

**Comment by ai** [comment]
@MoOx I am thiinking for solution. Maybe it will be fixed in event-based API, because we will know, what plugin changed to normalize values.

Right now we should fix broken plugins and make our plugins more solid by `toString()`.

**Comment by MoOx** [comment]
We cannot add a normalization in this class https://github.com/postcss/postcss/blob/master/lib/declaration.js ?
like a setter for value that just do

```js
set value(value) {
  this.value = String(value)
}
```

**Comment by ai** [comment]
We need to add some `_value` field. And I afraid it will confused developers as Raw fields.

**Comment by ai** [comment]
Maybe we an hide `_value` from showing in inspect?

**Comment by MoOx** [comment]
Yep. Anyway, developers should not use private/raw field. Like you love to say: only public api matters. The rest can be dropped anytime.

**Comment by ai** [comment]
Can you create a issue in PostCSS repo? I am preparing for Moscow frontend conference right now :(.

**Comment by MoOx** [comment]
Sure !

**Pull request closed without merging**
