### PR TITLE
Added support for selector transformation

### PR DESCRIPTION
**Pull request by uniquegestaltung**
Hi,

I implemented a new usefull feature for projects working with data attributes within css selectors.

- [x] config param
- [x] test

Martin

### CODE REVIEW

**Comment by MoOx** [comment]
Hi Martin. Thanks for your work!
Is this way to use calc part of the CSS specs?

**Comment by uniquegestaltung** [comment]
Hi MoOx, no it's no part of the CSS specs.
Only nice to have, like the implementation for media queries, which aren't part of the CSS specs too.

**Comment by MoOx** [comment]
I am sorry but I am going to pass. This plugin aims to be a fallback for official calc() function.
I suggest you to create a new plugin, for example postcss-calc-for-selector or something like that. :)
Thanks again anyway.

**Comment by uniquegestaltung** [comment]
Sorry for reopening, just to make this clear.

```css
@screen and (max-width: calc(500px*2)) {
  
  div[data-size=calc(500*2)] {
    
    width: calc(500px*2);

  }

}
```

The only valid calc operation in the above example is the third one for the width property.
The other two aren't valid calc usages. But currently your plugin supports media queries via config param.
So if you aim for a fallback for the official calc() function, the media query support is already non standard conform.

So I think you implemented the media query support because it's really useful.
My implementation is very useful too. 👍 😄 

Calc Spec: https://www.w3.org/TR/css3-values/#calc-notation
Media Query Spec: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by MoOx** [comment]
I forgot because I didn't do this.
Please adjust to be ok with a options disabled by default.

**Comment by uniquegestaltung** [comment]
Fine.
My changes already include a option disabled by default.

**Comment by MoOx** [comment]
Released as 5.3.0

**Pull request merged**
