### PR TITLE
fix: add support for svh, lvh, dvh, svw, lvw, dvw, svmin, lvmin, dvmin, svmax, lvmax, dvmax units

### LINKED ISSUE #217: [Bug]: Parse error when using dynamic viewport units (e.g. svh, lvw)
### Describe the bug

Parse error on line 1: 
1.9rem + 1.6svh
----------^
Expecting end of input, "RPAREN", "ADD", "SUB", "MUL", "DIV", got unexpected "UNKNOWN_DIMENSION"

### Expected behaviour

It should know those units and output no error.

### Steps to reproduce

Use any of the following units in your CSS code:

* svh
* lvh
* dvh
* svw
* lvw
* dvw
* svmin
* lvmin
* dvmin
* svmax
* lvmax
* dvmax

A full list of measure units is [available on dev.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility).

### Version

8.1.1

### Environment

```shell
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Pro
  Memory: 3.35 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
```

### Package details

```shell
├─┬ css-loader@6.11.0
│ ├─┬ icss-utils@5.1.0
│ │ └── postcss@8.4.39 deduped
│ ├─┬ postcss-modules-extract-imports@3.1.0
│ │ └── postcss@8.4.39 deduped
│ ├─┬ postcss-modules-local-by-default@4.0.5
│ │ └── postcss@8.4.39 deduped
│ ├─┬ postcss-modules-scope@3.2.0
│ │ └── postcss@8.4.39 deduped
│ ├─┬ postcss-modules-values@4.0.0
│ │ └── postcss@8.4.39 deduped
│ └── postcss@8.4.39 overridden
├─┬ css-minimizer-webpack-plugin@7.0.0
│ └── postcss@8.4.41 overridden
├─┬ cssnano@7.0.5
│ ├─┬ cssnano-preset-default@7.0.5
│ │ ├─┬ css-declaration-sorter@7.2.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ cssnano-utils@5.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-calc@10.0.1
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-colormin@7.0.2
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-convert-values@7.0.3
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-discard-comments@7.0.2
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-discard-duplicates@7.0.1
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-discard-empty@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-discard-overridden@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-merge-longhand@7.0.3
│ │ │ ├── postcss@8.4.41 deduped
│ │ │ └─┬ stylehacks@7.0.3
│ │ │   └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-merge-rules@7.0.3
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-minify-font-values@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-minify-gradients@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-minify-params@7.0.2
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-minify-selectors@7.0.3
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-charset@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-display-values@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-positions@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-repeat-style@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-string@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-timing-functions@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-unicode@7.0.2
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-url@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-normalize-whitespace@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-ordered-values@7.0.1
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-reduce-initial@7.0.2
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-reduce-transforms@7.0.0
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-svgo@7.0.1
│ │ │ └── postcss@8.4.41 deduped
│ │ ├─┬ postcss-unique-selectors@7.0.2
│ │ │ └── postcss@8.4.41 deduped
│ │ └── postcss@8.4.41 deduped
│ └── postcss@8.4.41 deduped
├─┬ next@14.2.5
│ └── postcss@8.4.31 overridden
├─┬ postcss-loader@8.1.1
│ └── postcss@8.4.41 deduped
└─┬ styled-components@6.1.12
  └── postcss@8.4.38 overridden
```

### Additional context

This is similar to #199. @ludofischer's #214 should provide a solid basis on how to fix this.

### PR DESCRIPTION
**Pull request by geecko86**
... as well as vb, svb, lvb, dvb, vi, svi, lvi, dvi.

fix #217 

I didn't add tests since you don't have any that's specific to vh and vw.

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by ludofischer — APPROVED** [review]
Thank you! I think we need to still regenerate the parser.

**Comment by geecko86** [comment]
> Thank you! I think we need to still regenerate the parser.

Sorry I'm not familiar enough with the project - not sure I understand. Anything I can assist you with?

Also, would you kindly provide an ETA for a push of this commit to production? Thank you?

**Comment by ludofischer** [comment]
Could you maybe post some sample CSS that you tried to parse, so I can add some tests, just to make sure we don't forget about it if we ever change the parser?
I realized after that nothing needs to be done with the parser is because the parser JavaScript code that runs when the plugin is used is generated from the grammar in the `.jison` file, but the generated parser code is not committed to the repository,  instead the generator runs during the `prepare` which should run when someone publishes.

**Comment by ludofischer** [comment]
> Sorry to insist, but do you have a broad estimation of when that might happen? Thank you.
If you really need immediately I could do it this evening or tomorrow.

Is this issue preventing the minification to complete? I think it's supposed to skip minifying the code it does not understand and output a warning, but it should not crash the program. Or is the warning itself a a problem?

**Comment by geecko86** [comment]
You're correct. The warning is not a problem in itself. I do however need to minify as much code as possible and was under the assumption that the plugin skipping lines was probably hurting its effectiveness.

> If you really need immediately I could do it this evening or tomorrow.

That's very kind, thank you. I certainly don't mean to be pushy - but yeah when you have a moment for this, it would be much appreciated.

**Pull request merged**
