### PR TITLE
handle uppercase calc

### PR DESCRIPTION
**Pull request by evilebottnawi**
calc can be in uppercase format

### CODE REVIEW

**Comment by andyjansson** [comment]
This doesn't really enable uppercase support, since the code lives in `reduce-css-calc`. The regex is only there to check whether it failed in transforming the calc into a singular value. You also need to update the regex in the following file: 

https://github.com/MoOx/reduce-css-calc/blob/master/src/index.js

**Comment by evilebottnawi** [comment]
@andyjansson let's do this here first and second i will send PR in https://github.com/MoOx/reduce-css-calc

**Comment by jonathantneal** [comment]
@evilebottnawi, will you be able to update the other file?

**Comment by evilebottnawi** [comment]
@jonathantneal what?

**Comment by andyjansson** [comment]
@evilebottnawi see my comment

**Comment by andyjansson** [comment]
Supported in master.

**Pull request closed without merging**
